### ISSUE TITLE
Project is not working.

### ISSUE THREAD

**Issue by pradeep-chauhan** [SaeidBsn/SwiftyGuideOverlay#2]
Hey i was trying to use this but not able to run.

**Comment by saeid** [comment]
@pradeep-chauhan what's your problem? 
what version of Swift/Xcode did you try to compile?

**Comment by pradeep-chauhan** [comment]
getting this cannot be opened because it is missing its project.pbxproj file.
Xcode - 8.3.1
Swift - 3.0

**Comment by saeid** [comment]
@pradeep-chauhan Pushed missing folder. now good to go.
